plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
